export { default as GovernanceHero } from './GovernanceHero'
export { default as EthicalDesignPrinciples } from './EthicalDesignPrinciples'
export { default as PrivacyArchitecture } from './PrivacyArchitecture'
export { default as AccessibilityStandards } from './AccessibilityStandards'
export { default as SafetyFailureModes } from './SafetyFailureModes'
export { default as TransparencyAccountability } from './TransparencyAccountability'
export { default as ClosingStatement } from './ClosingStatement'